# Generated by Django 5.2.dev20241016095222 on 2025-05-10 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_event_event_cancel_alter_event_date_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_override',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.daydateoverride', verbose_name='Перенос дня'),
        ),
    ]
