# Generated by Django 5.2.dev20241016095222 on 2025-05-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_abstracteventchanges_abstractevent_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractevent',
            name='changes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.abstracteventchanges', verbose_name='Изменения'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='final_date_time',
            field=models.TextField(default='', null=True, verbose_name='Дата и учебный час после изменений'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='final_holds_on_date',
            field=models.TextField(default='', null=True, verbose_name='Заданный день после изменений'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='final_participants',
            field=models.TextField(default='', null=True, verbose_name='Участники после изменений'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='final_places',
            field=models.TextField(default='', null=True, verbose_name='Места после изменений'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='origin_date_time',
            field=models.TextField(default='', null=True, verbose_name='Изначальная дата и учебный час'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='origin_holds_on_date',
            field=models.TextField(default='', null=True, verbose_name='Изначальные заданный день'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='origin_participants',
            field=models.TextField(default='', null=True, verbose_name='Изначальные участники'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='origin_places',
            field=models.TextField(default='', null=True, verbose_name='Изначальные места'),
        ),
    ]
