# Generated by Django 5.2.dev20241016095222 on 2025-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_abstractevent_changes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstracteventchanges',
            name='origin_date_time',
        ),
        migrations.AddField(
            model_name='abstracteventchanges',
            name='date_time',
            field=models.TextField(null=True, verbose_name='Дата и учебный час'),
        ),
        migrations.AddField(
            model_name='abstracteventchanges',
            name='group',
            field=models.TextField(null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='abstracteventchanges',
            name='subject',
            field=models.TextField(null=True, verbose_name='Занятие'),
        ),
    ]
