# Generated by Django 5.2.dev20241016095222 on 2025-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_event_is_event_overriden_alter_abstractevent_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='is_created',
            field=models.BooleanField(default=False, verbose_name='Абстрактное событие создано'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Абстрактное событие удалено'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='is_exported',
            field=models.BooleanField(default=False, verbose_name='Абстрактное событие экспортировано'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_event_overriden',
            field=models.BooleanField(default=False, verbose_name='Событие перезаписано'),
        ),
    ]
