# Generated by Django 5.2.dev20241016095222 on 2025-05-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_abstracteventchanges_is_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractevent',
            options={'verbose_name': 'Запланированное событие', 'verbose_name_plural': 'Запланированные события'},
        ),
        migrations.AlterModelOptions(
            name='abstracteventchanges',
            options={'verbose_name': 'Изменения в запланированном событии', 'verbose_name_plural': 'Изменения в запланированных событиях'},
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='is_created',
            field=models.BooleanField(default=False, verbose_name='Запланированное событие создано'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Запланированное событие удалено'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='is_exported',
            field=models.BooleanField(default=False, verbose_name='Запланированное событие экспортировано'),
        ),
        migrations.AlterField(
            model_name='event',
            name='abstract_event',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.abstractevent', verbose_name='Запланированное событие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_event_overriden',
            field=models.BooleanField(default=False, verbose_name='Событие изменено вручную'),
        ),
    ]
