# Generated by Django 5.2.dev20241016095222 on 2025-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_abstracteventchanges_origin_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstracteventchanges',
            old_name='final_participants',
            new_name='final_teachers',
        ),
        migrations.RenameField(
            model_name='abstracteventchanges',
            old_name='origin_participants',
            new_name='origin_teachers',
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='group',
            field=models.TextField(default='', null=True, verbose_name='Группа'),
        ),
    ]
