# Generated by Django 5.2.dev20241016095222 on 2025-05-23 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_abstractevent_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstracteventchanges',
            name='final_kind',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Тип после изменений'),
        ),
        migrations.AddField(
            model_name='abstracteventchanges',
            name='is_exported',
            field=models.BooleanField(default=False, verbose_name='Экспортировано'),
        ),
        migrations.AddField(
            model_name='abstracteventchanges',
            name='origin_kind',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Изначальный тип'),
        ),
        migrations.AlterField(
            model_name='abstractevent',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.eventkind', verbose_name='Тип'),
        ),
    ]
