# Generated by Django 5.2.dev20241016095222 on 2025-05-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_abstracteventchanges_final_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_event_overriden',
            field=models.BooleanField(default=False, editable=False, verbose_name='Событие перезаписано'),
        ),
        migrations.AlterField(
            model_name='abstractevent',
            name='kind',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.eventkind', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='origin_places',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Изначальные места'),
        ),
        migrations.AlterField(
            model_name='abstracteventchanges',
            name='origin_teachers',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Изначальные участники'),
        ),
        migrations.AlterField(
            model_name='event',
            name='abstract_event',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.abstractevent', verbose_name='Абстрактное событие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind_override',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.eventkind', verbose_name='Тип'),
        ),
    ]
