# Generated by Django 5.2.8 on 2025-11-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_abstractevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractevent',
            name='changes',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.abstracteventchanges', verbose_name='Изменения'),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='building',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='alt_name',
            field=models.TextField(blank=True, null=True, verbose_name='Академ. часы пары'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
    ]
