# Generated by Django 5.2.8 on 2025-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_abstractevent_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplace',
            name='building',
            field=models.CharField(blank=True, db_default='', default='', max_length=128, verbose_name='Корпус'),
        ),
    ]
