# Generated by Django 5.2.8 on 2025-11-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_eventplace_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractevent',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.timeslot', verbose_name='Временной интервал'),
        ),
    ]
