# Generated by Django 5.2.8 on 2025-11-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_abstractevent_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractevent',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.timeslot', verbose_name='Временной интервал'),
        ),
    ]
