# Generated by Django 5.2.8 on 2025-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_abstractevent_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default=999666999, max_length=16, verbose_name='Код подразделения'),
            preserve_default=False,
        ),
    ]
