# Generated by Django 5.2.8 on 2025-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shortname',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Аббревиатура'),
        ),
    ]
